In [1]:
import pandas as pd
import numpy as np

In [2]:
trips = pd.read_csv('./data/Divvy_Trips_2018_Q2.csv')
stations = pd.read_csv('./data/Divvy_Stations.csv')

#formating the data to make columns easier to access and keep only necessary columns
stations.columns = [x.replace(' ', '_').lower() for x in stations.columns]
stations['docks_missing'] = stations.total_docks - stations.docks_in_service
cols = stations.columns.tolist()
cols = cols[:5] + cols[-1:] + cols[5:-2]
stations = stations[cols]

In [8]:
stations.head()

,id,station_name,address,total_docks,docks_in_service,docks_missing,status,latitude,longitude
0,11,Jeffery Blvd & 71st St,Jeffery Blvd & 71st St,11,11,0,In Service,41.766638,-87.576450
1,106,State St & Pearson St,State St & Pearson St,27,27,0,In Service,41.897448,-87.628722
2,661,Evanston Civic Center,Evanston Civic Center,15,15,0,In Service,42.057044,-87.686554
3,622,California Ave & Cortez St,California Ave & Cortez St,15,15,0,In Service,41.900363,-87.696704
4,665,South Chicago Ave & Elliot Ave,South Chicago Ave & Elliot Ave,7,7,0,In Service,41.747363,-87.580046